### ISSUE TITLE
Serious improvements on Relion motioncor protocol

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-relion#239]
### This issue contains many other issues related to this protocol

* [ ] Use MPI/threads in a smarter way, see #63 
* [ ] Implement batches and PSD re-use, see #104 
* [ ] Check crash and performance when extracting > 1M particles, see #108 
* [ ] Check files generation for HTML report, see #210 
* [ ] Current PSD before/after (with Xmipp) fails, see #238
