### ISSUE TITLE
Improvements for Relion extract particles

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-relion#241]
### Several improvements for particles - extraction:

* [ ] Allow using particles as input (this will solve the issue of many properties not being propagated right now, e.g per-particles defocus, random subset, particle group, etc), see #41 
* [ ] Fix creation of empty stacks, see #189 
* [ ] Check crash and performance when extracting > 1M particles, see #108
